[deploy]
bucket = 'cfn-artifacts-eshwar'
region = 'us-east-1'
stack_name = 'CrdCluster'

[parameters]
CertificateArn = 'arn:aws:acm:us-east-1:183974383951:certificate/b7bd9ca8-a41a-4ef6-9601-65b686a9e883'
NetworkingStack = 'CrdNet'