name: Delete Activities

on:
  schedule:
    - cron: '0 4 * * *'  # Run every day at 12 AM UTC
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Replace with your desired Python version
      
      - name: Install psycopg2
        run: pip install psycopg2

      - name: Run Python script
        run: python bin/delete.py
